### ISSUE TITLE
Network on main thread exception

### ISSUE THREAD

**Issue by xstreamcl** [SendOTP/SendOTPAndroid#13]
This exception occurs sometimes as soon as sms arrives. I am using "compile 'com.msg91.sendotp.library:library:2.7'" in my build.gradle.

android.os.NetworkOnMainThreadException
                                                                         at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
                                                                         at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:682)
                                                                         at okio.Okio$2.read(Okio.java:139)
                                                                         at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                                                                         at okio.RealBufferedSource.read(RealBufferedSource.java:50)
                                                                         at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:381)
                                                                         at okhttp3.internal.Util.skipAll(Util.java:178)
                                                                         at okhttp3.internal.Util.discard(Util.java:160)
                                                                         at okhttp3.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:397)
                                                                         at okio.RealBufferedSource.close(RealBufferedSource.java:396)
                                                                         at okhttp3.internal.Util.closeQuietly(Util.java:90)
                                                                         at okhttp3.ResponseBody.bytes(ResponseBody.java:85)
                                                                         at okhttp3.ResponseBody.string(ResponseBody.java:109)
                                                                         at com.msg91.sendotp.library.internal.VerificationMethod$1.onPostExecute(VerificationMethod.java:82)
                                                                         at com.msg91.sendotp.library.internal.VerificationMethod$1.onPostExecute(VerificationMethod.java:65)
                                                                         at android.os.AsyncTask.finish(AsyncTask.java:636)
                                                                         at android.os.AsyncTask.access$500(AsyncTask.java:177)
                                                                         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by rakshitsoni02** [comment]
Can you send us device information .

**Comment by xstreamcl** [comment]
I am using Moto G(3rd Generation)
Android version - 6.0.1

**Comment by xstreamcl** [comment]
@rakshitsoni02 - dude any update? I am getting this error very frequently now.

**Comment by rakshitsoni02** [comment]
@xstreamcl  we are going to release new build with fix of this issue.

**Comment by bhaswanth88** [comment]
Even I am getting this. Is the new build released?

**Comment by rakshitsoni02** [comment]
Please update to 2.8, Let me know in case if it is still persist.

**Comment by xstreamcl** [comment]
It is happening in 2.8 as well
