### ISSUE TITLE
com.msg91.sendotp.library.internal.VerificationMethod$7.onReceive

### ISSUE THREAD

**Issue by vipulasri** [SendOTP/SendOTPAndroid#8]
I am getting this error on Production App with following device details

Device : VIVO V3
OS : Android 5.1.1

SendOTP Library : v2.5

```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.PHONE_STATE flg=0x10 (has extras) } in com.msg91.sendotp.library.internal.VerificationMethod$7@2c5e0873
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:886)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5401)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)
Caused by java.lang.StringIndexOutOfBoundsException: length=4; index=-2
       at java.lang.String.indexAndLength(String.java:500)
       at java.lang.String.substring(String.java:1313)
       at com.msg91.sendotp.library.internal.VerificationMethod$7.onReceive(SourceFile:308)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:876)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5401)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)
```

**Comment by rakshitsoni02** [comment]
please update to latest version.
